spring.application.name=Authify_Backend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/authify_app
spring.datasource.username=root
spring.datasource.password=Sumit@123

spring.jpa.hibernate.ddl-auto=update

jwt.secret.key = xuxPQqiSmRXtukDMrrPJcxHJnqEacAefYVTWQBVidzSdzTLpuqJaTmYZmWVYwjzDPEZWRiAVZHdPyAnnaCPNFmSbuyuwfjhGvWRKRqmXZwGjmceVASYXUWWHBgNETDrcaYfqPTLcQbpqgLztviNfQVgPECVaMdwKVJcqdrRJrzaMegEvkxdPeREuzHKqtjFuxdgvuQAuDmSKgENBhSkRmiAVgGQGWutyqkdDLQXbrgRPWwuEcAQaeAZgKNeVhkRQjQbgmWPwfUkfBrVCSfFrNGZdmjihaPivqRKQTGNaSHbjzDXnNLSuERjKyRhkieBJbtQqPnSRwNiWTErXnyBKZqbFVxEcMECDYGNHGBjxvTMxucWMLgFBtxEXKBGxPmmTKuhiKbemuhiRicJPWKTAKKuhrPMptDtNqGqwNVuDJmCXDpbkGejPMupKGGzzWfrcZBgXXuxEaRQergxAUdCGCFbLXWQJevbqNAVhBezZyTkCqWenygzbTXWWYCuByDJcGJRmBdVQLGUQHEnydDRxKBdWUPthMYLNvEpnGSaWuZPHvXHfhfiJydyYCwfwZgLFFQBzQzfVrmASuUnkCXpnWDdR

server.servlet.context-path=/api/profile

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a12725001@smtp-brevo.com
spring.mail.password=xsmtpsib-cf68cbb8b45249ef6beb21bf8277728b6d6914e2147f033b0f2316be1939da15-oqlXMbyoMn7cbGxm
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=sumitrkl2002@gmail.com
